sudo: required
services:
    - docker
    
before_install:
    - docker build -t sai/travisci -f Dockerfile.dev .

scripts:
    - docker run -e CI=true sai/travisci npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalks
    region: ap-south-1
    env:
    app:
    
    